FROM rust:latest AS builder
WORKDIR build
RUN apt update && apt install -y libssl-dev pkg-config
COPY . .

RUN cd worker && cargo build --release


FROM debian:bullseye
COPY --from=builder build/worker/target/release/worker ./
RUN apt update && apt install -y libssl-dev openssl
RUN openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem -subj "/C=GE/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com"
ENTRYPOINT [ "./worker" ]