# ------------------------------------------------------------------------------
# Cargo Build Stage
# ------------------------------------------------------------------------------
FROM messense/rust-musl-cross:mips-musl as cargo-build

WORKDIR /usr/src/myapp
COPY . .
RUN cd worker && rust-musl-builder cargo build --release

# ------------------------------------------------------------------------------
# Final Stage
# ------------------------------------------------------------------------------
FROM alpine:latest
RUN addgroup -g 1000 worker
RUN adduser -D -s /bin/sh -u 1000 -G worker worker
WORKDIR /home/app/bin/
COPY --from=cargo-build /usr/src/myapp/worker/target/x86_64-unknown-linux-musl/release/worker .
RUN chown worker:worker worker
USER worker
CMD ["./worker"]